### ISSUE TITLE
Error during first start, unable to generate config file

### ISSUE THREAD

**Issue by abrman** [MrKinau/FishingBot#10]
When running the jar downloaded via readme I get the following error.
Not  a java developer, am I doing something wrong?

```
java -jar Fishingbot.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/corba/se/impl/io/TypeMismatchException
	at systems.kinau.fishingbot.io.Config.init(Config.java:14)
	at systems.kinau.fishingbot.io.SettingsConfig.<init>(SettingsConfig.java:60)
	at systems.kinau.fishingbot.FishingBot.<init>(FishingBot.java:66)
	at systems.kinau.fishingbot.Main.main(Main.java:11)
Caused by: java.lang.ClassNotFoundException: com.sun.corba.se.impl.io.TypeMismatchException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
```

**Comment by MrKinau** [comment]
Hey @abrman thanks fpr your issue. Can you tell me which version of Java you are running?
`java --version`

and the OS you are using.
Have you installed the JDK?
This error is that the bot cant find a file which may not be included in a default Windows-Installation (JRE).

**Comment by abrman** [comment]
Hey,
I'm on a mac, lol
I believe I've downloaded java sdk when playing with a localhost server.

Here's my version dump:
```
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by MrKinau** [comment]
Okay, then this is the problem, working on a small patch, which gonna be out in a few minutes

**Comment by MrKinau** [comment]
I've updated the latest release: https://github.com/MrKinau/FishingBot/releases/tag/2.5

please let me know if it works for you :)

**Comment by abrman** [comment]
Started, config generated and restarting every 3s! :) Will try it out now.

**Comment by abrman** [comment]
Works like a charm! Even the autoreconnect (which I wasn't able to get with none of the other clients I found)
Is there any way to turn off "start-text" though? leaving it empty still sends a empty message :/

**Comment by MrKinau** [comment]
Nice to hear this :)

well its not implemented, but you can make a workaroud it with just sending a command instead of a message (i.e. /list or something else)
