### ISSUE TITLE
Keep geting thread errors

### ISSUE THREAD

**Issue by zaze06** [MrKinau/FishingBot#112]
Hi i keep geting thread errors in the consol i have

tested meythods to fix problem

restarted client
chanche version from 1.16.4 to automatic (the realm is 1.16.4)

the error is

[2021-01-04 21:47:01] [SEVERE ] The server 20.54.125.142 is not reachable with the Minecraft version. The automatic version detection may not work. Please set a default-protocol in config.json. 
[2021-01-04 21:47:01] [INFO   ] systems.kinau.fishingbot.network.utils.InvalidPacketException: VarInt too big 
[2021-01-04 21:47:01] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:118) 
[2021-01-04 21:47:01] [INFO   ] 	at systems.kinau.fishingbot.network.ping.ServerPinger.ping(ServerPinger.java:73) 
[2021-01-04 21:47:01] [INFO   ] 	at systems.kinau.fishingbot.Bot.<init>(Bot.java:196) 
[2021-01-04 21:47:01] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:78) 
[2021-01-04 21:47:01] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:178) 
[2021-01-04 21:47:01] [INFO   ] 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by zaze06** [comment]
btw i'm going to sleep so i can't resond for som howers

**Comment by MrKinau** [comment]
Thanks for your issue. To see what's wrong with it I'll need some more information. Can you enable Misc -> Log packets and send the generated log file?

**Comment by zaze06** [comment]
[log0.log](https://github.com/MrKinau/FishingBot/files/5768875/log0.log)
Hear you go but the paket option was in logs nit misc

**Comment by MrKinau** [comment]
Oh sorry for that, but you found it, thanks fo uploading your log. It's definitely a problem with the bot, but I can't test the functionality (because I do not own a realm). Without testing I can not provide a fix on this. If you can invite me (MrKinau) to a realm I could test it and create a fix for it.

**Comment by zaze06** [comment]
ok thx you ar now invited to the realm

**Comment by MrKinau** [comment]
Thanks for your participation and your patience. I've updated the latest release https://github.com/MrKinau/FishingBot/releases/tag/2.7.14

I extended the realm support, so it is much easier to configure it now (GUI for realm and ToS selection). Your mentioned bug should not appear anymore (unless the exception which shows that realms does not support the legacy server ping method I use, but you can ignore that). Please let me know if you have any further issues :)

**Comment by zaze06** [comment]
Ok thx for the help :)
