### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by frocal** [MrKinau/FishingBot#114]
I dunno what I'm doing wrong, but after setting it up and getting it ready for realms use, it tells me my username and password are invalid despite me triple-checking it and logging in normally with them just fine. I just get these errors trying to use the bot.

> [2021-01-08 05:08:26] [INFO   ] Configuration was loaded: C:\Users\User\Desktop\FishingBot\config.json 
> 
> [2021-01-08 05:08:26] [INFO   ] Trying to authenticate with ***************@email.com:************... 
> 
> [2021-01-08 05:08:26] [SEVERE ] Authentication failed with code 403 from https://authserver.mojang.com: HTTP/1.1 403 Forbidden 
> 
> [2021-01-08 05:08:26] [SEVERE ] {"error":"ForbiddenOperationException","errorMessage":"Invalid credentials. Invalid username or password."} 
> 
> [2021-01-08 05:08:26] [INFO   ] Username: username@email.com 
> 
> [2021-01-08 05:08:27] [SEVERE ] Could not connect to the realms endpoint (https://pc.realms.minecraft.net): HTTP/1.1 401 Unauthorized 
> 
> [2021-01-08 05:08:27] [INFO   ] There are no realms available for you to join. Remember to accept an invitation before you can join the realm. 
> 
> [2021-01-08 05:08:27] [INFO   ] Realms ID was not set. Shutting down... 
> 
> [2021-01-08 05:08:30] [INFO   ] java.lang.ClassCastException: javafx.scene.control.ButtonType cannot be cast to java.lang.String 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at java.util.Optional.ifPresent(Unknown Source) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at systems.kinau.fishingbot.gui.Dialogs.lambda$showRealmsWorlds$5(Dialogs.java:67) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at java.security.AccessController.doPrivileged(Native Method) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) 
> 
> [2021-01-08 05:08:30] [INFO   ] 	at java.lang.Thread.run(Unknown Source)

**Comment by MrKinau** [comment]
This can have several reasons, most likely Mojang has temporarily banned your IP. See [this](https://github.com/MrKinau/FishingBot/wiki/Troubleshooting#it-always-says-invalid-credentials-invalid-username-or-password). Try using another IP (VPN or change it) or just log not in for 10-15 minutes and try it again. It's pretty common that Mojang bans your IP. If your problem is still existing send an answer here.

**Comment by frocal** [comment]
It's still happening, yeah. I can log in normally just fine, but trying to use the bot just throws up that error message every single time.

**Comment by MrKinau** [comment]
That's pretty weird. The only thing it could be is that your input does not fit in the config format. Please check if everything was correctly written to the config file (config.json). Another issue could be that you have symbols in your password which may need to be escaped like ". Please check this.

**Comment by frocal** [comment]
It's just letters and numbers. And yeah, I've checked it and even deleted the config file and started the process all over again. Nothing.

**Comment by MrKinau** [comment]
It does exactly the same as the Minecraft Launcher, so it's really weird that you can not login. Have you tried logging out in the Minecraft Launcher and logging back in (using password). Another point which does not really fit to the error: MC Realms is currently down.

**Comment by MrKinau** [comment]
As there was no activity anymore I'll close this issue, if you still need support you can re-create it or join our Disocrd: https://discord.gg/xHpCDYf :)
