### ISSUE TITLE
1.17.1 Support

### ISSUE THREAD

**Issue by neuron42** [MrKinau/FishingBot#138]

**Comment by JustZacTTv** [comment]
this would be bussin

**Comment by nutjob4life** [comment]
I gave it a shot @MrKinau, adding the bare minimum to support 1.17.1 in the hopes that there were no changes in the protocol for fishing in 1.17.1 (based on your 1.17 branch). But no dice:
```
java.lang.IllegalStateException: java.io.EOFException 
    at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readLong(ByteStreams.java:351) 
    at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readLong(ByteArrayDataInputWrapper.java:116) 
    at systems.kinau.fishingbot.network.protocol.Packet.readUUID(Packet.java:96) 
```
So I guess there _were_ some changes! 😊 

Anyway, if this is something you could poke around in, I'd sure be grateful—as would @neuron42 and @JustZacTTv 😄

**Comment by nutjob4life** [comment]
Ooo, I think I saw some good news on Discord … which brought me here.

```console
$ git pull
$ mvn package
$ java -jar target/FishingBot-2.7.16.jar
[2021-07-21 20:44:40] [INFO   ] Using FishingBot v2.7.16 
…
[2021-07-21 20:45:47] [INFO   ] I start to fish! 
[2021-07-21 20:46:15] [INFO   ] Caught "cod" 
[2021-07-21 20:46:34] [INFO   ] Caught "cod" 
[2021-07-21 20:46:42] [INFO   ] Caught "pufferfish" 
```
Looks pretty good so far 🥳

**Comment by MrKinau** [comment]
Yeah 1.17.1 is fully supported now! 🥳
