### ISSUE TITLE
Cant sign in with 2 step auth

### ISSUE THREAD

**Issue by MrStabby77** [MrKinau/FishingBot#151]
found a little bug I think if you have two step authenticetor on it will not allow you to approve the sign in when using the  bot I get the message though the authenticator app and I approve it but if I go to sign in it just keeps asking for approval to sign in every time I try to start the bot

[2021-08-24 05:28:55] [INFO   ] Configuration was loaded: C:\Users\josht\Downloads\config.json 
[2021-08-24 05:28:55] [INFO   ] Trying to authenticate with (MICROSOFT)... 
[2021-08-24 05:28:55] [INFO   ] com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid username and/or password 
[2021-08-24 05:28:55] [INFO   ] 	at com.github.steveice10.mc.auth.service.MsaAuthenticationService.getLoginResponseFromCreds(MsaAuthenticationService.java:146) 
[2021-08-24 05:28:55] [INFO   ] 	at com.github.steveice10.mc.auth.service.MsaAuthenticationService.login(MsaAuthenticationService.java:224) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.auth.MicrosoftAuthenticator.authenticate(MicrosoftAuthenticator.java:21) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.auth.Authenticator.authenticate(Authenticator.java:50) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.Bot.authenticate(Bot.java:275) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.Bot.<init>(Bot.java:136) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:80) 
[2021-08-24 05:28:55] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:214) 
[2021-08-24 05:28:55] [INFO   ] 	at java.base/java.lang.Thread.run(Thread.java:831) 
[2021-08-24 05:28:55] [SEVERE ] The credentials you specified are invalid. This can have several reasons (see: https://github.com/MrKinau/FishingBot/wiki/Troubleshooting). 
[2021-08-24 05:28:55] [INFO   ] Username:
[2021-08-24 05:28:55] [INFO   ] Pinging  with protocol of MC-AUTOMATIC 
[2021-08-24 05:28:56] [SEVERE ] The server 127.0.0.1 is not reachable with the Minecraft version. The automatic version detection may not work. Please set a default-protocol in config.json. 
[2021-08-24 05:28:56] [INFO   ] java.net.ConnectException: Connection refused: connect 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/sun.nio.ch.Net.connect0(Native Method) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/sun.nio.ch.Net.connect(Net.java:576) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/sun.nio.ch.Net.connect(Net.java:565) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.net.Socket.connect(Socket.java:645) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.net.Socket.connect(Socket.java:595) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.net.Socket.<init>(Socket.java:519) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.net.Socket.<init>(Socket.java:293) 
[2021-08-24 05:28:56] [INFO   ] 	at systems.kinau.fishingbot.network.ping.ServerPinger.ping(ServerPinger.java:47) 
[2021-08-24 05:28:56] [INFO   ] 	at systems.kinau.fishingbot.Bot.<init>(Bot.java:248) 
[2021-08-24 05:28:56] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:80) 
[2021-08-24 05:28:56] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:214) 
[2021-08-24 05:28:56] [INFO   ] 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by DrMoraschi** [comment]
This was resolved in Discord
