### ISSUE TITLE
Microsoft logins works for me but not for an friend

### ISSUE THREAD

**Issue by Dabako** [MrKinau/FishingBot#158]
When trying to start the bot it shows this error

We are using Vanilla Minecraft 1.18.1 on an Vanilla Server

Authentication via Microsoft works for me, but not for an friend of me.

Der Access Token konnte nicht erneuert werden. Die Anmeldung erfolgt per Passwort. 
[2021-12-20 12:24:52] [INFORMATION] Anmeldung mit *********@gmail.com:************ wird versucht (MICROSOFT)... 
[2021-12-20 12:24:55] [INFORMATION] java.lang.NullPointerException 
[2021-12-20 12:24:55] [INFORMATION]     at com.github.steveice10.mc.auth.service.MsaAuthenticationService.getProfile(MsaAuthenticationService.java:206) 
[2021-12-20 12:24:55] [INFORMATION]     at com.github.steveice10.mc.auth.service.MsaAuthenticationService.login(MsaAuthenticationService.java:240) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.auth.MicrosoftAuthenticator.authenticate(MicrosoftAuthenticator.java:21) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.auth.Authenticator.authenticate(Authenticator.java:50) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.Bot.authenticate(Bot.java:277) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.Bot.connect(Bot.java:413) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.Bot.start(Bot.java:272) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:82) 
[2021-12-20 12:24:55] [INFORMATION]     at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:214) 
[2021-12-20 12:24:55] [INFORMATION]     at java.lang.Thread.run(Unknown Source)

**Comment by Summerfeeling** [comment]
Do you know if your friend enabled the two factor authentication for his account? If so, this is the problem.
The bot currently does not support 2fa for Microsoft accounts but that will be added soon.

**Comment by Dabako** [comment]
As far as I know he has not enabled two factor authentication

**Comment by MrKinau** [comment]
The authentication process got completely reworked, it should work now for everyone, just download the [latest release](https://github.com/MrKinau/FishingBot/releases/tag/v2.10.1)
