### ISSUE TITLE
Not sure how this works

### ISSUE THREAD

**Issue by HunterLavare** [MrKinau/FishingBot#159]
im having issues just getting this set up and not sure how to, ive put in a few thing i know i needed to. 

im using 1.18 on an origins mod server with a forge startup

[2022-01-14 18:41:57] [INFO   ] com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid username and/or password 
[2022-01-14 18:41:57] [INFO   ] 	at com.github.steveice10.mc.auth.service.MsaAuthenticationService.getLoginResponseFromCreds(MsaAuthenticationService.java:146) 
[2022-01-14 18:41:57] [INFO   ] 	at com.github.steveice10.mc.auth.service.MsaAuthenticationService.login(MsaAuthenticationService.java:224) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.auth.MicrosoftAuthenticator.authenticate(MicrosoftAuthenticator.java:21) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.auth.Authenticator.authenticate(Authenticator.java:50) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.Bot.authenticate(Bot.java:277) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.Bot.<init>(Bot.java:136) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:80) 
[2022-01-14 18:41:57] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:214) 
[2022-01-14 18:41:57] [INFO   ] 	at java.lang.Thread.run(Unknown Source) 
[2022-01-14 18:41:57] [SEVERE ] The credentials you specified are invalid. This can have several reasons (see: https://github.com/MrKinau/FishingBot/wiki/Troubleshooting). 
[2022-01-14 18:41:57] [INFO   ] Username: Hunter_Lavare 
[2022-01-14 18:41:57] [INFO   ] Pinging 104.194.2.205:25673 with protocol of MC-AUTOMATIC 
[2022-01-14 18:41:57] [INFO   ] Received pong: Welcome to Origins!, version: 1.18 / 1.18.1 (757), players online: 4

**Comment by amoraschi** [comment]
![IMG_20220115_094559.jpg](https://user-images.githubusercontent.com/68395930/149615755-0f57adee-8184-44e0-9aa5-396d329baa4e.jpg)

**Comment by MrKinau** [comment]
This bot does only support Minecraft vanilla (java edition). Forge mod handshakes are not working: see #38
