### ISSUE TITLE
server message not registering causing error

### ISSUE THREAD

**Issue by reefer** [MrKinau/FishingBot#17]
when the error happens it does not catch fish so im assuming its a easy fix on your end

[2019-11-13 19:55:42] [INFO   ] Achieved level 36
[2019-11-13 19:55:46] [INFO   ] Caught "RAW_FISH"
java.lang.IllegalStateException: Not a JSON Object: "?7"
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at systems.kinau.fishingbot.network.protocol.play.PacketInChat.read(PacketInChat.java:37)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:446)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readUncompressed(NetworkHandler.java:396)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:371)
        at systems.kinau.fishingbot.FishingBot.connect(FishingBot.java:218)
        at systems.kinau.fishingbot.FishingBot.start(FishingBot.java:144)
        at systems.kinau.fishingbot.Main.main(Main.java:12)
java.lang.IllegalStateException: Not a JSON Object: "?e?lDonate"
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at systems.kinau.fishingbot.network.protocol.play.PacketInChat.read(PacketInChat.java:37)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:446)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readUncompressed(NetworkHandler.java:396)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:371)
        at systems.kinau.fishingbot.FishingBot.connect(FishingBot.java:218)
        at systems.kinau.fishingbot.FishingBot.start(FishingBot.java:144)
        at systems.kinau.fishingbot.Main.main(Main.java:12)
java.lang.IllegalStateException: Not a JSON Object: "?7"
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at systems.kinau.fishingbot.network.protocol.play.PacketInChat.read(PacketInChat.java:37)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:446)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readUncompressed(NetworkHandler.java:396)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:371)
        at systems.kinau.fishingbot.FishingBot.connect(FishingBot.java:218)
        at systems.kinau.fishingbot.FishingBot.start(FishingBot.java:144)
        at systems.kinau.fishingbot.Main.main(Main.java:12)

**Comment by MrKinau** [comment]
Well already realized it, but havent pushed an update. The chat format is really awkward. Some servers just send the raw text and some (Bukkit, Spigot) send the text as json. I though it already worked on all servers, but it don't looks like it. lol.
