### ISSUE TITLE
Disconnecting problem

### ISSUE THREAD

**Issue by Badrifungo** [MrKinau/FishingBot#192]
When i start the bot it connects and disconnects every 5 seconds, i am using 1.19.3 bot release

**Comment by MrKinau** [comment]
Please append the full bot log, when that happens. Unfortunately it's impossible to help you, without the log.

**Comment by Badrifungo** [comment]
> Please append the full bot log, when that happens. Unfortunately it's impossible to help you, without the log.

[2023-02-11 16:27:43] [INFORMAZIONI] Configuration was loaded: C:\Users\gbarc\Downloads\config.json 
[2023-02-11 16:27:43] [INFORMAZIONI] Trying to authenciate at Microsoft... 
[2023-02-11 16:27:43] [INFORMAZIONI] Found refreshToken at C:\Users\gbarc\Downloads\refreshToken 
[2023-02-11 16:27:45] [INFORMAZIONI] Trying to refresh access token... 
[2023-02-11 16:27:46] [INFORMAZIONI] Access token successfully refreshed 
[2023-02-11 16:27:48] [INFORMAZIONI] Username: Patrizio_bar 
[2023-02-11 16:27:48] [INFORMAZIONI] Pinging 127.0.0.1:25565 with protocol of MC-1.19.3 
[2023-02-11 16:27:50] [GRAVE  ] The server 127.0.0.1 is not reachable with the Minecraft version. The automatic version detection may not work. Please set a default-protocol in the Settings. 
[2023-02-11 16:27:50] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at systems.kinau.fishingbot.network.ping.ServerPinger.ping(ServerPinger.java:54) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.<init>(Bot.java:252) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:95) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:27:50] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:27:50] [INFORMAZIONI] Obtained the required keys for chat signing! 
[2023-02-11 16:27:52] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:27:52] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:27:52] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:27:52] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:27:52] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:27:59] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:27:59] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:27:59] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:27:59] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:27:59] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:28:06] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:28:06] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:28:06] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:28:06] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:28:06] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:28:13] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:28:13] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:28:13] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:28:13] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:28:13] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:28:20] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:28:20] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:28:20] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:28:20] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:28:20] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:28:27] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:28:27] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:28:27] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:28:27] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:28:27] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-11 16:28:34] [INFORMAZIONI] java.net.ConnectException: Connection refused: connect 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.PlainSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.SocksSocketImpl.connect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.Socket.connect(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.net.Socket.<init>(Unknown Source) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:350) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-11 16:28:34] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-11 16:28:34] [GRAVE  ] An unexpected error occured: Connection refused: connect 
[2023-02-11 16:28:34] [GRAVE  ] The bot will be stopped... 
[2023-02-11 16:28:34] [INFORMAZIONI] FishingBot will reconnect in 5 seconds...

**Comment by MrKinau** [comment]
You've set your local machine (localhost) as your server, which is the default setting. You have to change this if you want the bot to join another server. For singleplayer you need to use Open to Lan and adjust the port in the server settings.

**Comment by Badrifungo** [comment]
> You've set your local machine (localhost) as your server, which is the default setting. You have to change this if you want the bot to join another server. For singleplayer you need to use Open to Lan and adjust the port in the server settings.

if I insert the ip of the server I play on, it disconnects me and tells me that another person has entered in my place and the bot doesn't work.
I send you the logs:
[2023-02-12 10:21:02] [INFORMAZIONI] Configuration was loaded: C:\Users\gbarc\Downloads\config.json 
[2023-02-12 10:21:02] [INFORMAZIONI] Trying to authenciate at Microsoft... 
[2023-02-12 10:21:02] [INFORMAZIONI] Found refreshToken at C:\Users\gbarc\Downloads\refreshToken 
[2023-02-12 10:21:03] [INFORMAZIONI] Trying to refresh access token... 
[2023-02-12 10:21:04] [INFORMAZIONI] Access token successfully refreshed 
[2023-02-12 10:21:07] [INFORMAZIONI] Username: Patrizio_bar 
[2023-02-12 10:21:07] [INFORMAZIONI] Pinging uominiveri.aternos.me:35053 with protocol of MC-1.19.3 
[2023-02-12 10:21:07] [INFORMAZIONI] Received pong: §7Benvenuto nel server di §9Samuele081602§7!, version: 1.19.3 (761), players online: 2 
[2023-02-12 10:21:07] [INFORMAZIONI] Obtained the required keys for chat signing! 
[2023-02-12 10:21:07] [INFORMAZIONI] Module "HandshakeModule" enabled! 
[2023-02-12 10:21:07] [INFORMAZIONI] Module "LoginModule" enabled! 
[2023-02-12 10:21:07] [INFORMAZIONI] Module "ClientDefaultsModule" enabled! 
[2023-02-12 10:21:07] [INFORMAZIONI] Module "FishingModule" enabled! 
[2023-02-12 10:21:07] [INFORMAZIONI] Module "ChatProxyModule" enabled! 
[2023-02-12 10:21:07] [INFORMAZIONI] Login successful! 
[2023-02-12 10:21:07] [INFORMAZIONI] Name: Patrizio_bar 
[2023-02-12 10:21:07] [INFORMAZIONI] UUID: 8b96b585-e36c-3e82-8b02-40c9872877e4 
[2023-02-12 10:21:08] [INFORMAZIONI] Achieved level: 34 
[2023-02-12 10:21:08] [INFORMAZIONI] Disconnected: {"translate":"multiplayer.disconnect.invalid_public_key_signature"} 
[2023-02-12 10:21:08] [INFORMAZIONI] Module "LoginModule" disabled! 
[2023-02-12 10:21:08] [INFORMAZIONI] Module "ClientDefaultsModule" disabled! 
[2023-02-12 10:21:08] [INFORMAZIONI] Module "FishingModule" disabled! 
[2023-02-12 10:21:08] [INFORMAZIONI] Module "ChatProxyModule" disabled! 
[2023-02-12 10:21:08] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-12 10:21:08] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:08] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$updateInventory$8(FishingModule.java:381) 
[2023-02-12 10:21:08] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:09] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:09] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-02-12 10:21:09] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:09] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:09] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$startPositionUpdate$2(ClientDefaultsModule.java:130) 
[2023-02-12 10:21:09] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:13] [INFORMAZIONI] Module "HandshakeModule" enabled! 
[2023-02-12 10:21:13] [INFORMAZIONI] Module "LoginModule" enabled! 
[2023-02-12 10:21:13] [INFORMAZIONI] Module "ClientDefaultsModule" enabled! 
[2023-02-12 10:21:13] [INFORMAZIONI] Module "FishingModule" enabled! 
[2023-02-12 10:21:13] [INFORMAZIONI] Module "ChatProxyModule" enabled! 
[2023-02-12 10:21:13] [INFORMAZIONI] Login successful! 
[2023-02-12 10:21:13] [INFORMAZIONI] Name: Patrizio_bar 
[2023-02-12 10:21:13] [INFORMAZIONI] UUID: 8b96b585-e36c-3e82-8b02-40c9872877e4 
[2023-02-12 10:21:14] [INFORMAZIONI] Disconnected: {"translate":"multiplayer.disconnect.invalid_public_key_signature"} 
[2023-02-12 10:21:14] [INFORMAZIONI] Module "LoginModule" disabled! 
[2023-02-12 10:21:14] [INFORMAZIONI] Module "ClientDefaultsModule" disabled! 
[2023-02-12 10:21:14] [INFORMAZIONI] Module "FishingModule" disabled! 
[2023-02-12 10:21:14] [INFORMAZIONI] Module "ChatProxyModule" disabled! 
[2023-02-12 10:21:14] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-12 10:21:15] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$updateInventory$8(FishingModule.java:381) 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:15] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:15] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$startPositionUpdate$2(ClientDefaultsModule.java:130) 
[2023-02-12 10:21:15] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:19] [INFORMAZIONI] Module "HandshakeModule" enabled! 
[2023-02-12 10:21:19] [INFORMAZIONI] Module "LoginModule" enabled! 
[2023-02-12 10:21:19] [INFORMAZIONI] Module "ClientDefaultsModule" enabled! 
[2023-02-12 10:21:19] [INFORMAZIONI] Module "FishingModule" enabled! 
[2023-02-12 10:21:19] [INFORMAZIONI] Module "ChatProxyModule" enabled! 
[2023-02-12 10:21:19] [INFORMAZIONI] Login successful! 
[2023-02-12 10:21:19] [INFORMAZIONI] Name: Patrizio_bar 
[2023-02-12 10:21:19] [INFORMAZIONI] UUID: 8b96b585-e36c-3e82-8b02-40c9872877e4 
[2023-02-12 10:21:20] [INFORMAZIONI] Achieved level: 34 
[2023-02-12 10:21:20] [INFORMAZIONI] Disconnected: {"translate":"multiplayer.disconnect.invalid_public_key_signature"} 
[2023-02-12 10:21:20] [INFORMAZIONI] Module "LoginModule" disabled! 
[2023-02-12 10:21:20] [INFORMAZIONI] Module "ClientDefaultsModule" disabled! 
[2023-02-12 10:21:20] [INFORMAZIONI] Module "FishingModule" disabled! 
[2023-02-12 10:21:20] [INFORMAZIONI] Module "ChatProxyModule" disabled! 
[2023-02-12 10:21:20] [INFORMAZIONI] FishingBot will reconnect in 5 seconds... 
[2023-02-12 10:21:20] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:20] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$updateInventory$8(FishingModule.java:381) 
[2023-02-12 10:21:20] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:21] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:21] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$startPositionUpdate$2(ClientDefaultsModule.java:130) 
[2023-02-12 10:21:21] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source) 
[2023-02-12 10:21:21] [INFORMAZIONI] java.lang.NullPointerException 
[2023-02-12 10:21:21] [INFORMAZIONI] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-02-12 10:21:21] [INFORMAZIONI] 	at java.lang.Thread.run(Unknown Source)

**Comment by MrKinau** [comment]
Is the server truly 1.19.3?

**Comment by Badrifungo** [comment]
> Is the server truly 1.19.3?

yes, it is

**Comment by maxcynicle** [comment]
Is this related? https://github.com/PaperMC/Velocity/issues/754
> The problem occurred when I enabled enforce-secure-profile , should it be disabled or it is not yet implemented ?

I'm guessing servers with enforce-secure-profile set to true will fail for this bot as it's not an official client. Just my two cents.

**Comment by MrKinau** [comment]
Disabling enforce-secure-profiles would maybe fix the issue, but this is not a solution. I've tested both settings recently and they are generally working. I'm guessing the profile chat signing Keys could not be downloaded, but there is a log message that states that they are present. Haven't tested to connect via a Velocity proxy, maybe there is a bug with it, is the server you're trying to connect to behind a velocity proxy or is there anything special with it?

**Comment by YoungerKayn** [comment]
I'm also experiencing this problem. I guess that's because there's a seconds-lag when I join the server, the bot could not receive packet and shut down. I wonder is it possible to set a delay after the bot join the server.

Here's the logs I got:

*Usually, I got this*
>[INFO   ] UUID: 23d7ea56-a13b-38e8-b3c6-3dafc5006096 
[INFO   ] [CHAT] Younger_Lin joined the game 
[INFO   ] java.io.EOFException 
[INFO   ]     at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203) 
[INFO   ]     at systems.kinau.fishingbot.network.protocol.NetworkHandler.readCompressed(NetworkHandler.java:842)
[INFO   ]     at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:813) 
[INFO   ]     at systems.kinau.fishingbot.Bot.connect(Bot.java:395) 
[INFO   ]     at systems.kinau.fishingbot.Bot.start(Bot.java:280) 
[INFO   ]     at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[INFO   ]     at systems.kinau.fishingbot.Main.main(Main.java:63) 
[WARNING] Could not receive packet! Shutting down... 

*Once I got this*
>[INFO   ] [CHAT] Younger_Lin joined the game 
[INFO   ] Achieved level: 6 
[INFO   ] systems.kinau.fishingbot.network.utils.InvalidPacketException: VarInt too big 
[INFO   ]     at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:124) 
[INFO   ]     at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:806)
[INFO   ]     at systems.kinau.fishingbot.Bot.connect(Bot.java:395) 
[INFO   ]     at systems.kinau.fishingbot.Bot.start(Bot.java:280) 
[INFO   ]     at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[INFO   ]     at systems.kinau.fishingbot.Main.main(Main.java:63) 
[WARNING] Could not receive packet! Shutting down...

**Comment by MrKinau** [comment]
> I'm also experiencing this problem. I guess that's because there's a seconds-lag when I join the server, the bot could not receive packet and shut down. I wonder is it possible to set a delay after the bot join the server.

This looks like a different issue, please send the full log with (Logs » Log packets) enabled

**Comment by MrKinau** [comment]
Not sure if this issue, had the same root issue as #226 but maybe it's now fixed with 2.11.1
