### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by fafa1213** [MrKinau/FishingBot#194]
Can someone help me with this problem >.< ThxQ

[2023-02-26 22:24:34] [INFO   ] Configuration was loaded: C:\Users\yiuka\Desktop\FishingBot\config.json 
[2023-02-26 22:24:34] [INFO   ] Trying to authenciate at Microsoft... 
[2023-02-26 22:24:34] [INFO   ] Found refreshToken at C:\Users\yiuka\Desktop\FishingBot\refreshToken 
[2023-02-26 22:24:34] [INFO   ] Trying to refresh access token... 
[2023-02-26 22:24:35] [INFO   ] Access token successfully refreshed 
[2023-02-26 22:24:37] [INFO   ] Username: Himawariii_i 
[2023-02-26 22:24:37] [INFO   ] Pinging fafaminecraft.ddns.net:25565 with protocol of MC-1.19.1 / 1.19.2 
[2023-02-26 22:24:37] [INFO   ] Received pong: Better MC [FORGE] 1.19.2, version: 1.19.1 / 1.19.2 (760), players online: 2 
[2023-02-26 22:24:38] [INFO   ] Obtained the required keys for chat signing! 
[2023-02-26 22:24:38] [INFO   ] Module "HandshakeModule" enabled! 
[2023-02-26 22:24:38] [INFO   ] Module "LoginModule" enabled! 
[2023-02-26 22:24:38] [INFO   ] Module "ClientDefaultsModule" enabled! 
[2023-02-26 22:24:38] [INFO   ] Module "FishingModule" enabled! 
[2023-02-26 22:24:38] [INFO   ] Module "ChatProxyModule" enabled! 
[2023-02-26 22:24:38] [INFO   ] java.net.SocketException: 連線已被您主機上的軟體中止。 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:322) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:79) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:116) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readUncompressed(NetworkHandler.java:721) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:715) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:407) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-02-26 22:24:38] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:210) 
[2023-02-26 22:24:38] [INFO   ] 	at java.base/java.lang.Thread.run(Thread.java:833) 
[2023-02-26 22:24:38] [WARNING] Could not receive packet! Shutting down... 
[2023-02-26 22:24:38] [INFO   ] Module "LoginModule" disabled! 
[2023-02-26 22:24:38] [INFO   ] Module "ClientDefaultsModule" disabled! 
[2023-02-26 22:24:38] [INFO   ] Module "FishingModule" disabled! 
[2023-02-26 22:24:38] [INFO   ] Module "ChatProxyModule" disabled!

**Comment by MrKinau** [comment]
I'm not a native chinese speaker, but according to Google Translate the remote host closed the connection (in this case the server, you're trying to connect to). Maybe it's a Forge only server which requires mods, which is not supported by the Fishingbot?

**Comment by fafa1213** [comment]
ohh! I got it. ThxQ
