### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by YukioKenshin2** [MrKinau/FishingBot#203]
I have also Disconnects pls help

[2023-06-11 02:20:17] [INFORMATION] Erforderliche Schlüssel für Chatsignaturen erhalten! 
[2023-06-11 02:20:17] [INFORMATION] Modul "HandshakeModule" aktiviert! 
[2023-06-11 02:20:17] [INFORMATION] Modul "LoginModule" aktiviert! 
[2023-06-11 02:20:17] [INFORMATION] Modul "ClientDefaultsModule" aktiviert! 
[2023-06-11 02:20:17] [INFORMATION] Modul "FishingModule" aktiviert! 
[2023-06-11 02:20:17] [INFORMATION] Modul "ChatProxyModule" aktiviert! 
[2023-06-11 02:20:17] [INFORMATION] Modul "EjectionModule" aktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Login erfolgreich! 
[2023-06-11 02:20:18] [INFORMATION] Name: AnimeIsLive 
[2023-06-11 02:20:18] [INFORMATION] UUID: 3f028cc6-bac1-4bcd-8c29-5ecba48fc8ae 
[2023-06-11 02:20:18] [INFORMATION] java.lang.IllegalStateException: java.io.EOFException 
[2023-06-11 02:20:18] [INFORMATION] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readByte(ByteStreams.java:301) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readByte(ByteArrayDataInputWrapper.java:74) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:67) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:59) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.play.PacketInCommands.readCommandNode(PacketInCommands.java:52) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.play.PacketInCommands.read(PacketInCommands.java:42) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:891) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readCompressed(NetworkHandler.java:856) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:813) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:395) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.Bot.start(Bot.java:280) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-06-11 02:20:18] [INFORMATION] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:211) 
[2023-06-11 02:20:18] [INFORMATION] 	at java.lang.Thread.run(Unknown Source) 
[2023-06-11 02:20:18] [INFORMATION] Caused by: java.io.EOFException 
[2023-06-11 02:20:18] [INFORMATION] 	at java.io.DataInputStream.readByte(Unknown Source) 
[2023-06-11 02:20:18] [INFORMATION] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readByte(ByteStreams.java:299) 
[2023-06-11 02:20:18] [INFORMATION] 	... 13 more 
[2023-06-11 02:20:18] [WARNUNG] Packet konnte nicht gelesen werden! Der Bot wird gestoppt... 
[2023-06-11 02:20:18] [INFORMATION] Modul "LoginModule" deaktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Modul "ClientDefaultsModule" deaktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Modul "FishingModule" deaktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Modul "ChatProxyModule" deaktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Modul "EjectionModule" deaktiviert! 
[2023-06-11 02:20:18] [INFORMATION] Der FishingBot verbindet sich in 5 Sekunden neu... 
[2023-06-11 02:20:19] [INFORMATION] java.lang.NullPointerException 
[2023-06-11 02:20:19] [INFORMATION] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-06-11 02:20:19] [INFORMATION] 	at java.lang.Thread.run(Unknown Source) 
[2023-06-11 02:20:19] [INFORMATION] java.lang.NullPointerException 
[2023-06-11 02:20:19] [INFORMATION] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$startPositionUpdate$2(ClientDefaultsModule.java:126) 
[2023-06-11 02:20:19] [INFORMATION] 	at java.lang.Thread.run(Unknown Source) 
[2023-06-11 02:20:23] [INFORMATION] Modul "HandshakeModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Modul "LoginModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Modul "ClientDefaultsModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Modul "FishingModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Modul "ChatProxyModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Modul "EjectionModule" aktiviert! 
[2023-06-11 02:20:23] [INFORMATION] Login erfolgreich! 
[2023-06-11 02:20:23] [INFORMATION] Name: AnimeIsLive

**Comment by MrKinau** [comment]
Do you know, what server software runs on the server you try to connect to? I'll double check if there are any new options in the Commands Packet, which causes this issue

**Comment by MrKinau** [comment]
I only tested with an account without op, but the commands packet did not include newly added argument types. Those commands have not been send to me while testing, because of the testing account not having op, lol

**Comment by MrKinau** [comment]
fixed in https://github.com/MrKinau/FishingBot/releases/tag/v2.10.8
