### ISSUE TITLE
Connnection Error

### ISSUE THREAD

**Issue by polar-escobear** [MrKinau/FishingBot#224]
I've used Fishingbot in the past with no prior issues, however after trying to use it on a stipe server, I'm thrown the following error

java.lang.IllegalStateException: java.io.EOFException 
[2023-11-21 12:23:51] [INFO   ] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readFully(ByteStreams.java:349) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readFully(ByteArrayDataInputWrapper.java:54) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readBytes(ByteArrayDataInputWrapper.java:154) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.utils.nbt.Tag.readName(Tag.java:42) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.utils.nbt.Tag.readName(Tag.java:33) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.utils.nbt.Tag.readNamed(Tag.java:47) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.utils.nbt.NBTTag.<init>(NBTTag.java:20) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.Packet.readSlot(Packet.java:229) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.play.PacketInWindowItems.read(PacketInWindowItems.java:36) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:954) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readCompressed(NetworkHandler.java:916) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:873) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.Bot.connect(Bot.java:396) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.Bot.start(Bot.java:281) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:97) 
[2023-11-21 12:23:51] [INFO   ] 	at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$3(GUIController.java:211) 
[2023-11-21 12:23:51] [INFO   ] 	at java.lang.Thread.run(Unknown Source) 
[2023-11-21 12:23:51] [INFO   ] Caused by: java.io.EOFException 
[2023-11-21 12:23:51] [INFO   ] 	at java.io.DataInputStream.readFully(Unknown Source) 
[2023-11-21 12:23:51] [INFO   ] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readFully(ByteStreams.java:347) 
[2023-11-21 12:23:51] [INFO   ] 	... 16 more 
[2023-11-21 12:23:51] [WARNING] Could not receive packet! Shutting down... 
[2023-11-21 12:23:51] [INFO   ] Module "LoginModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] Module "ClientDefaultsModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] Module "FishingModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] Module "ChatProxyModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] Module "ChatCommandModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] Module "EjectionModule" disabled! 
[2023-11-21 12:23:51] [INFO   ] FishingBot will reconnect in 5 seconds... 
[2023-11-21 12:23:52] [INFO   ] java.lang.NullPointerException 
[2023-11-21 12:23:52] [INFO   ] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-11-21 12:23:52] [INFO   ] 	at java.lang.Thread.run(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] java.util.concurrent.RejectedExecutionException: Task systems.kinau.fishingbot.Bot$$Lambda$617/18586145@16334ba rejected from java.util.concurrent.ThreadPoolExecutor@6c4cb5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] 
[2023-11-21 12:23:52] [INFO   ] 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] 	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] 	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] 	at systems.kinau.fishingbot.Bot.runCommand(Bot.java:285) 
[2023-11-21 12:23:52] [INFO   ] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$null$0(ClientDefaultsModule.java:66) 
[2023-11-21 12:23:52] [INFO   ] 	at java.util.ArrayList.forEach(Unknown Source) 
[2023-11-21 12:23:52] [INFO   ] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$onSetDifficulty$1(ClientDefaultsModule.java:65) 
[2023-11-21 12:23:52] [INFO   ] 	at java.lang.Thread.run(Unknown Source) 

Any ideas?

**Comment by MrKinau** [comment]
This looks like a bug with the new NBT parser I've implemented for 1.20.2. At least one item in the bots inventory could not be parsed for some reason. In order to fix this I need to know the server version and your bots version. Additionally a copy of the accounts playerdata would massively help to reproduce this issue (if you have access to the servers world directory)

**Comment by polar-escobear** [comment]
I don't have access to the playerdata sadly, however my server version is 1.20.1 and the bot version is v2.10.13

**Comment by MrKinau** [comment]
Haven't tested 1.20.1 with the newest version, I'll take a look into it. As a temporary fix, as the server is still at 1.20.1 you can use an older build of the bot v2.10.11 which most likely does not suffer from this issue as the new 1.20.2 NBT changes are not implemented in this version.

**Comment by MrKinau** [comment]
I've just tested serveral items with much NBT data, but was not able to reproduce your issue. Maybe you can try find out which item leads to this bug and send me the NBT data or a screenshot of the item?

**Comment by MrKinau** [comment]
With the help of another reporter, I was able to reproduce this issue and fixed it in the latest release. Please let me know if the issue persists for you in v2.10.14
