### ISSUE TITLE
invalid_public_key_signature.new

### ISSUE THREAD

**Issue by mille-neige** [MrKinau/FishingBot#226]
fishingbot can't run correctly and shows errors massege: invalid_public_key_signature.new 

[2023-12-11 19:37:40] [信息     ] Configuration was loaded: E:\Downloads\config.json 
[2023-12-11 19:37:40] [信息     ] Trying to authenciate at Microsoft... 
[2023-12-11 19:37:40] [信息     ] Found refreshToken at E:\Downloads\refreshToken 
[2023-12-11 19:37:41] [信息     ] Trying to refresh access token... 
[2023-12-11 19:38:06] [信息     ] Access token successfully refreshed 
[2023-12-11 19:38:15] [信息     ] Username: Sea233 
[2023-12-11 19:38:15] [信息     ] Pinging 175.178.219.64:25565 with protocol of MC-1.20 / 1.20.1 
[2023-12-11 19:38:15] [信息     ] Received pong: A Minecraft Server, version: 1.20 / 1.20.1 (763), players online: 0 
[2023-12-11 19:38:17] [信息     ] Obtained the required keys for chat signing! 
[2023-12-11 19:38:17] [信息     ] Module "HandshakeModule" enabled! 
[2023-12-11 19:38:17] [信息     ] Module "LoginModule" enabled! 
[2023-12-11 19:38:17] [信息     ] Module "ClientDefaultsModule" enabled! 
[2023-12-11 19:38:17] [信息     ] Module "FishingModule" enabled! 
[2023-12-11 19:38:17] [信息     ] Module "ChatProxyModule" enabled! 
[2023-12-11 19:38:17] [信息     ] Module "ChatCommandModule" enabled! 
[2023-12-11 19:38:18] [信息     ] Login successful! 
[2023-12-11 19:38:18] [信息     ] Name: Sea233 
[2023-12-11 19:38:18] [信息     ] UUID: 80f5a922-82ca-3be3-8c5f-e6a9b90c6965 
[2023-12-11 19:38:18] [信息     ] Disconnected: multiplayer.disconnect.invalid_public_key_signature.new 
[2023-12-11 19:38:18] [信息     ] Module "LoginModule" disabled! 
[2023-12-11 19:38:18] [信息     ] Module "ClientDefaultsModule" disabled! 
[2023-12-11 19:38:18] [信息     ] Module "FishingModule" disabled! 
[2023-12-11 19:38:18] [信息     ] Module "ChatProxyModule" disabled! 
[2023-12-11 19:38:18] [信息     ] Module "ChatCommandModule" disabled! 
[2023-12-11 19:38:18] [信息     ] FishingBot will reconnect in 5 seconds... 
[2023-12-11 19:38:18] [信息     ] java.lang.NullPointerException: Cannot invoke "systems.kinau.fishingbot.bot.Player.getHeldSlot()" because the return value of "systems.kinau.fishingbot.Bot.getPlayer()" is null 
[2023-12-11 19:38:18] [信息     ] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$updateInventory$8(FishingModule.java:381) 
[2023-12-11 19:38:18] [信息     ] 	at java.base/java.lang.Thread.run(Thread.java:833) 
[2023-12-11 19:38:19] [信息     ] java.lang.NullPointerException: Cannot invoke "systems.kinau.fishingbot.bot.Player.getHeldItem()" because the return value of "systems.kinau.fishingbot.Bot.getPlayer()" is null 
[2023-12-11 19:38:19] [信息     ] 	at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.lang.Thread.run(Thread.java:833) 
[2023-12-11 19:38:19] [信息     ] java.util.concurrent.RejectedExecutionException: Task systems.kinau.fishingbot.Bot$$Lambda$1020/0x000002349e43ef88@348a1c0a rejected from java.util.concurrent.ThreadPoolExecutor@1bb1ba3c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:721) 
[2023-12-11 19:38:19] [信息     ] 	at systems.kinau.fishingbot.Bot.runCommand(Bot.java:285) 
[2023-12-11 19:38:19] [信息     ] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$null$0(ClientDefaultsModule.java:69) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) 
[2023-12-11 19:38:19] [信息     ] 	at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$onSetDifficulty$1(ClientDefaultsModule.java:68) 
[2023-12-11 19:38:19] [信息     ] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MrKinau** [comment]
I've seen something like this before after connecting with a Microsoft account to a cracked server (online-mode: false), could you tell me if the server you're trying to connect to is a cracked server (online-mode: false)?

**Comment by mille-neige** [comment]
yes,it's a craked server

**Comment by MrKinau** [comment]
It's most likely working after unchecking the online mode in the settings, but the bot will use a different account then I'll keep this open, as it should work to join offline mode servers with Microsoft accounts as well.

**Comment by MrKinau** [comment]
fixed with 2.11.1
