### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by RootRobo** [MrKinau/FishingBot#34]
When I try to start the bot, I get this error message: (both with the one I compiled and with the latest release)
`Authentication failed with code 403 from https://authserver.mojang.com/authenticate: HTTP/1.1 403 Forbidden`
If I wait 10 minutes, it usually works again. Is this an error from the bot or is it only the Minecraft Authentication server? (sorry for wasting ur time, im just dumb)

**Comment by RootRobo** [comment]
And I get this error:
`[SCHWERWIEGEND] Login failed: {"translate":"multiplayer.disconnect.unverified_username"}`

**Comment by MrKinau** [comment]
Well this means mojang blocks you, the bot does not shutdown if the authentication process failed. Igf you log in too often Mojang blocks your IP address and the bot uses the username (normally mailaddess on migrated accounts, which in your case is 24 chars long and so could not used as username). If you are blocked you can only join offline servers (you may turn the offline-mode on) and use the desired username as username (max. 16 chars, no very special chars). Hope this answers your question. Last but not least you should not try to login while blocked. Just wait a few minutes

**Comment by RootRobo** [comment]
Okay, I'll try to use a VPN to bypass the IP blocking, thanks for your reply!

**Comment by RootRobo** [comment]
I just started NordVPN and connected it. Then I tried it again but it didn't work. Also worth to mention: I can normally login and play with this account in the Minecraft Launcher

**Comment by RootRobo** [comment]
The bot still has the issue, even after restarting my PC, waiting and using a VPN,,,

**Comment by MrKinau** [comment]
ehh and you use your correct credentials? email and password?
Maybe your password uses character used by the .properties fileformat which need to be escaped? Is the number of censored stars in console the exact same number of your password chars?

**Comment by RootRobo** [comment]
1. Yes, I copied the login information from the config into the launcher
2. Yes.
As I said, I can normally login and play with the same account using a normal Minecraft Vanilla Client. This issue began a few hours ago, without me changing anything. I just restarted the bot and then those errors appeared.

**Comment by RootRobo** [comment]
And no, my password doesn't contain any  special characters.

**Comment by MrKinau** [comment]
Oh you could use the authentication and it worked and now it does not?

Thats crazy, maybe there are some config options incorrect? No error?
Try deleteing the config and set the password & username (mail) again

**Comment by RootRobo** [comment]
The authentication works, but it can't login anymore. I also tried to reset the config, it changed nothing. The error still occurs.

**Comment by RootRobo** [comment]
Its strange.

**Comment by RootRobo** [comment]
I am going to try it again tomorrow. I will also try to restart my Router and try it on my Laptop. I hope I can fix it (or find the error in the code)

**Comment by RootRobo** [comment]
I just tried it on my Raspberry PI. The first start was successful, then I Hot this error (again):
```
pi@Raspi4Server:~/autofish $ java -jar Fishingbot.jar              [2020-03-18 22:31:50] [INFORMATION] Try to authenticate jonyjunior777@gmail.com:
********* 
[2020-03-18 22:31:50] [INFORMATION] Authentication successful! 
[2020-03-18 22:31:50] [INFORMATION] Pinging 147.135.30.172:25572 with protocol o
f MC-1.8 
[2020-03-18 22:31:51] [INFORMATION] Received pong: Escape To Your Reality, Versi
on: Unknown version, online: 7 
[2020-03-18 22:31:51] [SCHWERWIEGEND] This server is not running a supported pro
tocol version: ProtocolVersion 706 
[2020-03-18 22:31:51] [SCHWERWIEGEND] It is possibe that it wont work correctly 
[2020-03-18 22:31:51] [INFORMATION] Module "FishingModule" enabled! 
[2020-03-18 22:31:51] [INFORMATION] Module "HandshakeModule" enabled! 
[2020-03-18 22:31:51] [INFORMATION] Module "LoginModule" enabled! 
[2020-03-18 22:31:51] [INFORMATION] Module "ChatProxyModule" enabled! 
[2020-03-18 22:31:51] [INFORMATION] Module "ChatCommandModule" enabled! 
[2020-03-18 22:31:51] [INFORMATION] Module "ClientDefaultsModule" enabled![2020-03-18 22:31:52] [SCHWERWIEGEND] Login failed: {"translate":"multiplayer.di
sconnect.unverified_username"} 
[2020-03-18 22:31:52] [INFORMATION] Module "ClientDefaultsModule" disabled! 
[2020-03-18 22:31:52] [INFORMATION] Module "FishingModule" disabled! 
[2020-03-18 22:31:52] [INFORMATION] FishingBot restarts in 3 seconds... 
[2020-03-18 22:31:55] [INFORMATION] Try to authenticate jonyjunior777@gmail.com:
********* 
[2020-03-18 22:31:55] [INFORMATION] Authentication successful! 
[2020-03-18 22:31:56] [SCHWERWIEGEND] This server is not running a supported pro
tocol version: ProtocolVersion 706 
[2020-03-18 22:31:56] [SCHWERWIEGEND] It is possibe that it wont work correctly 
[2020-03-18 22:31:56] [INFORMATION] Module "FishingModule" enabled! 
[2020-03-18 22:31:56] [INFORMATION] Module "HandshakeModule" enabled! 
[2020-03-18 22:31:56] [INFORMATION] Module "LoginModule" enabled! 
[2020-03-18 22:31:56] [INFORMATION] Module "ChatProxyModule" enabled! 
[2020-03-18 22:31:56] [INFORMATION] Module "ChatCommandModule" enabled! 
[2020-03-18 22:31:56] [INFORMATION] Module "ClientDefaultsModule" enabled![2020-03-18 22:31:56] [SCHWERWIEGEND] Login failed: {"translate":"multiplayer.di
sconnect.unverified_username"}
```
This time I provided the entire log. I really do not know whats going wrong.

**Comment by RootRobo** [comment]
And no, its not because the protocol version isnt supported. This happens on 1.15.2 servers too.

**Comment by MrKinau** [comment]
Do you restart the bot manually or do you restart the server/kick the bot etc? Maybe its an bug in the reconnect mechanic

**Comment by MrKinau** [comment]
nvm I thought it worked at the first start?

**Comment by MrKinau** [comment]
And this definitely have to be changed: https://wiki.vg/Pre-release_protocol#Login_Success

**Comment by RootRobo** [comment]
I restart the bot manually using CTRL+C and then java -jar FishingBot.jar
And yes, it worked on the first start.

**Comment by MrKinau** [comment]
weird

**Comment by RootRobo** [comment]
Yes, very weird. Also worth to mention is that it only works 1 time per device, no matter which account I use.

**Comment by RootRobo** [comment]
I just restarted my router and changed the hostname of my Raspberry Pi and now I get this error:
```
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readFully(ByteStreams.java:277)
at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readFully(ByteArrayDataInputWrapper.java:40)
at systems.kinau.fishingbot.network.utils.ByteArrayDataInputWrapper.readBytes(ByteArrayDataInputWrapper.java:140)
at systems.kinau.fishingbot.network.protocol.Packet.readString(Packet.java:41)
at systems.kinau.fishingbot.network.protocol.login.PacketInLoginSuccess.read(PacketInLoginSuccess.java:34)
at systems.kinau.fishingbot.network.protocol.NetworkHandler.readPacket(NetworkHandler.java:491)
at systems.kinau.fishingbot.network.protocol.NetworkHandler.readUncompressed(NetworkHandler.java:439)
at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:414)
at systems.kinau.fishingbot.FishingBot.connect(FishingBot.java:210)
at systems.kinau.fishingbot.FishingBot.start(FishingBot.java:143)
at systems.kinau.fishingbot.Main.main(Main.java:12)
Caused by: java.io.EOFException
at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readFully(ByteStreams.java:275)
... 10 more
[2020-03-19 01:16:05] [WARNUNG] Could not receive packet! Shutting down! 
[2020-03-19 01:16:05] [INFORMATION] Module "ClientDefaultsModule" disabled!
```
Could this happen because the server just updated to 20w12a or is it an other issue?

**Comment by RootRobo** [comment]
All issues are now fixed I dont know how I did this but everything works fin now. Thanks for the huge help!
