### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by survivalbloke** [MrKinau/FishingBot#42]
What information can I provide you for troubleshooting?

I'm on Ubunut 18.04. and MC java v. 1.15.2.  I'm getting this:

[2020-04-18 19:26:16] [SEVERE ] Could not start bot: Connection refused (Connection refused) 
[2020-04-18 19:26:16] [INFO   ] FishingBot restarts in 3 seconds...

**Comment by MrKinau** [comment]
Connection refused could be almost anything...
You can add a copy of your config.properties (CENSOR LOGIN DATA)
Maybe trying to connect to another host can help to figure out the issue

**Comment by survivalbloke** [comment]
OK, I'm really feeling dumb, but I had incorrectly entered the port number in the config.properties.

However, now that I am able to execute the jar file, I'm not sure it's actually running.  No automatic finishing is happening.  Here's what I'm seeing:

`java -jar Fishingbot.jar 
Exception in thread "main" java.lang.NumberFormatException: For input string: "19191919191919191919191919191919191919500"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at systems.kinau.fishingbot.io.ConvertUtils.convert(ConvertUtils.java:24)
	at systems.kinau.fishingbot.io.PropertyProcessor.processAnnotations(PropertyProcessor.java:69)
	at systems.kinau.fishingbot.io.Config.init(Config.java:14)
	at systems.kinau.fishingbot.io.SettingsConfig.<init>(SettingsConfig.java:73)
	at systems.kinau.fishingbot.FishingBot.<init>(FishingBot.java:69)
	at systems.kinau.fishingbot.Main.main(Main.java:11)
`

**Comment by MrKinau** [comment]
Okay, somewhere you have entered a too high config property. The config expects somewhere a number, but receives "19191919191919191919191919191919191919500" which could not be interpreted as number. You should use smaller numbers. Max is 2147483647 which however should be high enough

**Comment by survivalbloke** [comment]
Man, thank you for so many replies!  OK, I fixed that but now:
`[2020-04-18 20:50:04] [INFO   ] Module "FishingModule" enabled! 
[2020-04-18 20:50:04] [INFO   ] Module "HandshakeModule" enabled! 
[2020-04-18 20:50:04] [INFO   ] Module "LoginModule" enabled! 
[2020-04-18 20:50:04] [INFO   ] Module "ClientDefaultsModule" enabled! 
[2020-04-18 20:50:04] [SEVERE ] Login failed: {"text":"This server has mods that require Forge to be installed on the client. Contact your server admin for more details."} 
[2020-04-18 20:50:04] [INFO   ] Module "ClientDefaultsModule" disabled! 
[2020-04-18 20:50:04] [INFO   ] Module "FishingModule" disabled! 
[2020-04-18 20:50:04] [INFO   ] FishingBot restarts in 3 seconds... 
`
I *do* have forge installed on my client and on the server(separate machines).  I am able to start minecraft on my client and use the forge mods so I'm not sure why I get this error.

**Comment by MrKinau** [comment]
The fishingbot is a standalone minecraft client and completely independent from your minecraft client. Mods and other features installed to your minecraft installation do not affect the bot. If your targetted server require mods to be installed you could not connect to it using this bot atm, but a spoof for the forge-handshake is already planned (see #38). Sorry for this. The update will be released with the 1.16 release

**Comment by nakassh** [comment]
Hi, I'm facing the same issue. How could I contribute to fix this?

**Comment by MrKinau** [comment]
I am not.sure if this is fixable at all (skipping all mod handshakes may cause issues), but the main thread is at https://github.com/MrKinau/FishingBot/issues/38 if you want to write this Forge spoofing bypass you are welcome to create a Pull Request :)
