### ISSUE TITLE
Realms displaying "Login failed" due to "outdated_client" with "1.16.1"

### ISSUE THREAD

**Issue by nutjob4life** [MrKinau/FishingBot#55]
Hi @MrKinau! 👋

With FishingBot built from source (git clone on 2020-07-04, branch master), startup fails with the following:
```console
[2020-07-04 09:14:17] [INFO   ] Try to authenticate [REDACTED]@gmail.com:**************** 
[2020-07-04 09:14:17] [INFO   ] Authentication successful! 
[2020-07-04 09:14:18] [INFO   ] Accepted TOS! 
[2020-07-04 09:14:18] [INFO   ] Connecting to: {"address":"20.191.40.200:30216","resourcePackUrl":null,"resourcePackHash":null} 
[2020-07-04 09:14:18] [INFO   ] Pinging 20.191.40.200:30216 with protocol of MC-1.8 
[2020-07-04 09:14:19] [SEVERE ] Could not ping: 20.191.40.200 
[2020-07-04 09:14:19] [INFO   ] Module "FishingModule" enabled! 
[2020-07-04 09:14:19] [INFO   ] Module "HandshakeModule" enabled! 
[2020-07-04 09:14:19] [INFO   ] Module "LoginModule" enabled! 
[2020-07-04 09:14:19] [INFO   ] Module "ChatCommandModule" enabled! 
[2020-07-04 09:14:19] [INFO   ] Module "ClientDefaultsModule" enabled! 
[2020-07-04 09:14:19] [SEVERE ] Login failed: {"translate":"multiplayer.disconnect.outdated_client","with":["1.16.1"]} 
[2020-07-04 09:14:19] [INFO   ] Module "ClientDefaultsModule" disabled! 
[2020-07-04 09:14:19] [INFO   ] Module "FishingModule" disabled! 
[2020-07-04 09:14:19] [INFO   ] FishingBot restarts in 3 seconds... 
```
It then goes into a loop, retrying every 3 seconds with `multiplayer.disconnect.outdated_client` as the cause.

FishingBot built as follows:
```csh
fatalii 227 % date -u
Sat Jul  4 14:22:00 UTC 2020
fatalii 228 % git clone git@github.com:MrKinau/FishingBot.git
Cloning into 'FishingBot'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 1449 (delta 43), reused 87 (delta 36), pack-reused 1337
Receiving objects: 100% (1449/1449), 371.86 KiB | 2.17 MiB/s, done.
Resolving deltas: 100% (803/803), done.
fatalii 229 % cd FishingBot/
/Users/kelly/Documents/Development/FishingBot
fatalii 230 % mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< systems.kinau:FishingBot >----------------------
[INFO] Building FishingBot 2.7.3
[INFO] --------------------------------[ jar ]---------------------------------
…
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.647 s
[INFO] Finished at: 2020-07-04T09:22:17-05:00
[INFO] ------------------------------------------------------------------------
29.514u 1.678s 0:05.56 560.7%	0+0k 0+0io 0pf+0w
fatalii 231 % cp /tmp/config.properties .
fatalii 232 % java -jar target/FishingBot-2.7.3.jar 
[2020-07-04 09:22:32] [INFO   ] Try to authenticate [REDACTED]:**************** 
[2020-07-04 09:22:32] [INFO   ] Authentication successful! 
[2020-07-04 09:22:33] [INFO   ] Accepted TOS! 
[2020-07-04 09:22:33] [INFO   ] Connecting to: {"address":"20.191.40.200:30216","resourcePackUrl":null,"resourcePackHash":null} 
[2020-07-04 09:22:33] [INFO   ] Pinging 20.191.40.200:30216 with protocol of MC-1.8 
[2020-07-04 09:22:34] [SEVERE ] Could not ping: 20.191.40.200 
[2020-07-04 09:22:34] [INFO   ] Module "FishingModule" enabled! 
[2020-07-04 09:22:34] [INFO   ] Module "HandshakeModule" enabled! 
[2020-07-04 09:22:34] [INFO   ] Module "LoginModule" enabled! 
[2020-07-04 09:22:34] [INFO   ] Module "ChatCommandModule" enabled! 
[2020-07-04 09:22:34] [INFO   ] Module "ClientDefaultsModule" enabled! 
[2020-07-04 09:22:34] [SEVERE ] Login failed: {"translate":"multiplayer.disconnect.outdated_client","with":["1.16.1"]} 
[2020-07-04 09:22:34] [INFO   ] Module "ClientDefaultsModule" disabled! 
[2020-07-04 09:22:34] [INFO   ] Module "FishingModule" disabled! 
[2020-07-04 09:22:34] [INFO   ] FishingBot restarts in 3 seconds... 
^CException in thread "Thread-2" java.lang.NullPointerException
	at systems.kinau.fishingbot.FishingBot.lambda$connect$0(FishingBot.java:212)
	at java.lang.Thread.run(Thread.java:748)
fatalii 233 %
```

Here's the `config.properties`:

```
account-password=[READACTED]
account-username=[READACTED]
announce-lvl-up=I've got a new level\: %lvl%
announce-type-chat=ONLY_ENCHANTED
announce-type-console=ALL
auto-disconnect-players-threshold=5
auto-disconnect=false
auto-reconnect-time=3
auto-reconnect=true
default-protocol=1.8
discord-webHook=https://discordapp.com/api/webhooks/[REDACTED]
log-count=15
log-packets=false
online-mode=true
proxy-chat=false
realm-accept-tos=true
realm-id=160124
server-ip=127.0.0.1
server-port=25565
start-text-enabled=true
start-text=%prefix%Starting fishing;/trigger Bot
stucking-fix-enabled=true
```

I can ask the owner to invite you to realm `160124` if that'll help.

This may be related to #54 🤷‍♀️ except that issue's closed and I explicitly see 1.16.1 in the current source code.

**Comment by MrKinau** [comment]
As the ping changed and I havent implemented the new ping (the default minecraft Server still support the old ping method) the client cant guess the correct version. You have to eyplicitly set the default-protocol to 1.16.1 with using realms. Hope that will help you.

I will leave this issue open to remind me to implement the new ping

**Comment by nutjob4life** [comment]
NEVERMIND.

The issue apparently is documentation? 😅 I missed the `default-protocol` which needs to be set to `1.16.1.
