### ISSUE TITLE
 Disconnect after connecting to the server

### ISSUE THREAD

**Issue by Oopas** [MrKinau/FishingBot#64]
The server version I'm connected to is 1.11.2. But I didn't find it in the list of supported versions. 
So I tried to connect to the server using 1.11.1.
I found it connected to the server correctly. At the beginning, I forgot to set the `announcement-lvl-up` to false. Once I connected to the server, the `announcement-lvl-up` would be triggered. At this time, I could see the message sent by the program in the chat bar of the server.
But then it will be disconnected from the server, and the program reports an error..

**Comment by Oopas** [comment]
This is the output of the program:


[2020-08-10 09:46:43] [信息     ] Starting in offline-mode with username: EMan
[2020-08-10 09:46:43] [信息     ] Pinging yde.chaowan.me:10489 with protocol of MC-1.11.1
[2020-08-10 09:46:43] [信息     ] Module "FishingModule" enabled!
[2020-08-10 09:46:43] [信息     ] Module "HandshakeModule" enabled!
[2020-08-10 09:46:43] [信息     ] Module "LoginModule" enabled!
[2020-08-10 09:46:43] [信息     ] Module "ChatCommandModule" enabled!
[2020-08-10 09:46:43] [信息     ] Module "ClientDefaultsModule" enabled!
[2020-08-10 09:46:43] [信息     ] Login successful!
[2020-08-10 09:46:43] [信息     ] Name: EMan
[2020-08-10 09:46:43] [信息     ] UUID: ***********************
[2020-08-10 09:46:43] [信息     ] Achieved level 8
[2020-08-10 09:46:45] [信息     ] Starting fishing!
systems.kinau.fishingbot.network.utils.InvalidPacketException: VarInt too big
        at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:112)
        at systems.kinau.fishingbot.network.protocol.NetworkHandler.readData(NetworkHandler.java:453)
        at systems.kinau.fishingbot.FishingBot.connect(FishingBot.java:220)
        at systems.kinau.fishingbot.FishingBot.start(FishingBot.java:153)
        at systems.kinau.fishingbot.Main.main(Main.java:12)
[2020-08-10 09:46:45] [警告     ] Could not receive packet! Shutting down!
[2020-08-10 09:46:45] [信息     ] Module "ClientDefaultsModule" disabled!
[2020-08-10 09:46:45] [信息     ] Module "FishingModule" disabled!
[2020-08-10 09:46:45] [信息     ] FishingBot restarts in 10 seconds...
Exception in thread "Thread-2" java.lang.NullPointerException
        at systems.kinau.fishingbot.FishingBot.lambda$connect$0(FishingBot.java:212)
        at java.lang.Thread.run(Unknown Source)

This is the config I use

[config.zip](https://github.com/MrKinau/FishingBot/files/5048769/config.zip)

**Comment by MrKinau** [comment]
Thanks for your issue, I'll take a closer look at it, might be possible I broke something up in the ancient versions with fixes for newer versions.

**Comment by MrKinau** [comment]
And 1.11.2 is not listed, because it shares the same protocol with 1.11.1 (https://wiki.vg/Protocol_version_numbers)

**Comment by MrKinau** [comment]
Indeed this is a bug.
Tested it and it appears that the PosLook-Packet was not registered in versions before 1.12. I will upload a fixed version asap, again thanks for your issuereport

**Comment by MrKinau** [comment]
I've updated the latest release (v2.7.3) with this fixes. Everything should work now (except the automatic version detection, dunno why this is broken, but you can set the default-protocol to 1.11 and it should work.
