### ISSUE TITLE
1.16.2 support

### ISSUE THREAD

**Issue by nutjob4life** [MrKinau/FishingBot#67]
I'm sure this is already on your radar, but my fellow realms players and I would love to see 1.16.2 supported, so here's our official issue/plea 🙏

(I tried doing it myself, adding protocol version `751`, plenty of `1_16_2` cases all over, and copying constants from `1_16`, but there seemed to be additional nuances about connection setup during difficulty-setting or position-updates that were way over my head 🤯)

**Comment by MrKinau** [comment]
oh well, did not notice it's already out.

I'll work for it for now :)

**Comment by MrKinau** [comment]
Well that was quite more work as expected...

1. packet ids changed (okay)
2. the worldCount in Join Game packet is not readable anymore as varint (just workarounded this, maybe there is more information in the future about it)
3. I broke the auto-version detection in the last commit (lol)
4. The Object id of the bobber entity changed (...)
5. The item ids changed (new registries.json)

Well, that all for just a non-major release, lol

**Comment by nutjob4life** [comment]
Thanks @MrKinau! Really surprising there was that much going from x.y.1 → x.y.2.

Did you get a chance to test this on a Realms server? I'm seeing:

```console
fatalii 250 % date -u
Sat Aug 15 01:39:28 UTC 2020
fatalii 251 % git pull
Already up to date.
fatalii 252 % mvn package
[INFO] Scanning for projects...
…
[INFO] BUILD SUCCESS
[INFO] Total time: 5.835 s
[INFO] Finished at: 2020-08-14T20:39:42-05:00
fatalii 253 % egrep '^default-protocol' config.properties
default-protocol=1.16.2
fatalii 254 % java -jar target/FishingBot-2.7.4.jar
[2020-08-14 20:39:49] [INFO   ] Try to authenticate REDACTED:**************** 
[2020-08-14 20:39:49] [INFO   ] Authentication successful! 
[2020-08-14 20:39:49] [INFO   ] Accepted TOS! 
[2020-08-14 20:39:50] [INFO   ] Connecting to: {"address":"20.54.90.102:31801","resourcePackUrl":null,"resourcePackHash":null} 
[2020-08-14 20:39:50] [INFO   ] Pinging 20.54.90.102:31801 with protocol of MC-1.16.2 
Exception in thread "main" systems.kinau.fishingbot.network.utils.InvalidPacketException: VarInt too big
	at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:112)
	at systems.kinau.fishingbot.network.ping.ServerPinger.ping(ServerPinger.java:68)
	at systems.kinau.fishingbot.FishingBot.<init>(FishingBot.java:143)
	at systems.kinau.fishingbot.Main.main(Main.java:11)
fatalii 255 % echo \U+1F914
🤔
```

**Comment by MrKinau** [comment]
indeed. Can confirm it.
Seems like the automatic version detection is more broken than expected. I'll try to fix this

**Comment by MrKinau** [comment]
Well just workarounded it again. This should help and won't break the whole bot if the automatic version detection fails. Updated the latest release with the workaround

**Comment by nutjob4life** [comment]
Pulled, rebuilt, and rerunning and … looks good! Thanks again @MrKinau!

(And when you have a sec, maybe toss `logs/` into `.gitignore` 😉)

**Comment by MrKinau** [comment]
np and yes, seems useful :)
